import { Card } from "./card/card.jsx";
import { Input } from "./input/input.jsx";
import { InputToggle } from "./input-toggle/input-toggle.jsx";
import { InputCheckbox } from "./input-checkbox/input-checkbox.jsx";
import { InputRadio } from "./input-radio/input-radio.jsx";
import { InputColor } from "./input-color/input-color.jsx";
import { Button } from "./button/button.jsx";
import { Label } from "./label/label.jsx";
import { Icon } from "./icon/icon.jsx";
import { Menu } from "./menu/menu.jsx";

export { Card } from "./card/card.jsx";
export { Input } from "./input/input.jsx";
export { InputToggle } from "./input-toggle/input-toggle.jsx";
export { InputCheckbox } from "./input-checkbox/input-checkbox.jsx";
export { InputRadio } from "./input-radio/input-radio.jsx";
export { InputColor } from "./input-color/input-color.jsx";
export { Button } from "./button/button.jsx";
export { Label } from "./label/label.jsx";
export { Icon } from "./icon/icon.jsx";
export { Menu } from "./menu/menu.jsx";

customElements.define("formilk-card", Card);
customElements.define("formilk-input-basic", Input);
customElements.define("formilk-input-toggle", InputToggle);
customElements.define("formilk-input-checkbox", InputCheckbox);
customElements.define("formilk-input-radio", InputRadio);
customElements.define("formilk-input-color", InputColor);
customElements.define("formilk-button", Button);
customElements.define("formilk-label", Label);
customElements.define("formilk-icon", Icon);
customElements.define("formilk-menu", Menu);
